services:
    pi_shrink:
        platform: linux/amd64
        container_name: "piShrink"
        hostname: "pi-shrink"
        build: pishrink
        volumes:
            - ./:/root/:rw
        privileged: true